services:
  - type: web
    name: threads-downloader # Uygulamanın ismi
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
